apiVersion: v1
description: A Helm chart for sveltekit-web3auth
icon: https://raw.githubusercontent.com/sveltejs/svelte/29052aba7d0b78316d3a52aef1d7ddd54fe6ca84/site/static/images/svelte-android-chrome-512.png
name: sveltekit-web3auth
version: 0.0.1
