import {
  VITE_WEB3AUTH_ISSUER,
  VITE_WEB3AUTH_CLIENT_ID,
  VITE_WEB3AUTH_CLIENT_SECRET,
  VITE_WEB3AUTH_POST_LOGOUT_REDIRECT_URI,
  VITE_WEB3AUTH_TOKEN_REFRESH_MAX_RETRIES,
} from "./env";

export const config = {
  issuer: VITE_WEB3AUTH_ISSUER,
  clientId: VITE_WEB3AUTH_CLIENT_ID,
  clientSecret: VITE_WEB3AUTH_CLIENT_SECRET,
  postLogoutRedirectUri: VITE_WEB3AUTH_POST_LOGOUT_REDIRECT_URI,
  maxRetries: VITE_WEB3AUTH_TOKEN_REFRESH_MAX_RETRIES,
};
