export const VITE_WEB3AUTH_ISSUER: string = import.meta.env
  .VITE_WEB3AUTH_ISSUER;

export const VITE_WEB3AUTH_CLIENT_ID: string = import.meta.env
  .VITE_WEB3AUTH_CLIENT_ID;

export const VITE_WEB3AUTH_CLIENT_SECRET: string = import.meta.env
  .VITE_WEB3AUTH_CLIENT_SECRET;

export const VITE_WEB3AUTH_REDIRECT_URI: string = import.meta.env
  .VITE_WEB3AUTH_REDIRECT_URI;

export const VITE_WEB3AUTH_POST_LOGOUT_REDIRECT_URI: string = import.meta.env
  .VITE_WEB3AUTH_POST_LOGOUT_REDIRECT_URI;

export const VITE_WEB3AUTH_CLIENT_SCOPE: string = import.meta.env
  .VITE_WEB3AUTH_CLIENT_SCOPE;

export const VITE_WEB3AUTH_TOKEN_REFRESH_MAX_RETRIES: number = import.meta.env
  .VITE_WEB3AUTH_TOKEN_REFRESH_MAX_RETRIES;

export const VITE_WEB3AUTH_REFRESH_TOKEN_ENDPOINT: string = import.meta.env
  .VITE_WEB3AUTH_REFRESH_TOKEN_ENDPOINT;

export const VITE_WEB3AUTH_REFRESH_PAGE_ON_SESSION_TIMEOUT: boolean =
  import.meta.env.VITE_WEB3AUTH_REFRESH_PAGE_ON_SESSION_TIMEOUT;
