/// <reference types="@sveltejs/kit" />
interface ImportMetaEnv {
  VITE_WEB3AUTH_ISSUER: string;
  VITE_WEB3AUTH_CLIENT_ID: string;
  VITE_WEB3AUTH_CLIENT_SECRET: string;
  VITE_WEB3AUTH_REDIRECT_URI: string;
  VITE_WEB3AUTH_POST_LOGOUT_REDIRECT_URI?: string;
  VITE_WEB3AUTH_CLIENT_SCOPE: string;
  VITE_WEB3AUTH_TOKEN_REFRESH_MAX_RETRIES: number;
  VITE_WEB3AUTH_REFRESH_TOKEN_ENDPOINT: string;
  VITE_WEB3AUTH_REFRESH_PAGE_ON_SESSION_TIMEOUT: boolean;
  VITE_HASURA_GRAPHQL_URL: string;
  VITE_HASURA_GRAPHQL_INTERNAL_URL: string;
  VITE_HASURA_GRAPHQL_WS_URL: string;
}
